Repository dedis/d-voting, pull requests merged in 2022-01, with the labels that each got.

#27 Poll formats unit tests
  contracts/evoting/controller/action.go
  contracts/evoting/types/ballots.go
  contracts/evoting/types/ballots_test.go
  contracts/evoting/types/election.go
  contracts/evoting/types/election_test.go
  docs/ballot_encoding.md
  docs/state of smart contract.md
  test/integration_test.go
Labels: documentation, tests

#36 Custom Performance tests
  .github/workflows/go_integration_tests.yml
  test/dvotingdela.go
  test/performance_test.go
Labels: enhancement, tests

#37 (documentation) Adds missing files in sidebar
  docs/sidebar.md
Labels: documentation
