Repository dedis/d-voting, pull requests merged in 2022-10, with the labels that each got.

#176 Changing favicon to D-voting logo
  web/frontend/public/favicon.ico
  web/frontend/src/logo.svg
Labels: web frontend

#185 Report of the second production-readiness meeting
  docs/minutes/week-2-production-readiness.md
Labels: documentation

#177 Add types in index.tsx
  web/frontend/src/index.tsx
Labels: web frontend

#186 Add Contributors to the About page
  web/backend/tsconfig.json
  web/frontend/src/language/en.json
  web/frontend/src/pages/About.tsx
Labels: web frontend

#189 Adding minutes in markdown
  docs/minutes/week-2-frontend.md
  docs/minutes/week-2-global-meeting-docs/Untitled.png
  docs/minutes/week-2-global-meeting.md
  docs/minutes/week-2-global-meeting.md.backup
Labels: documentation

#184 Refactoring of contracts/evoting/types/ballots_test.go :
  contracts/evoting/types/ballots.go
  contracts/evoting/types/ballots_test.go
Labels: node backend

#183 Refactoring in cli/cosipbftcontroller
  cli/cosipbftcontroller/action.go
  cli/cosipbftcontroller/mod.go
  contracts/evoting/controller/action.go
Labels: node backend

#190 upload week 4 frontend minutes
  docs/minutes/week-4-frontend.md
Labels: documentation
