Repository dedis/d-voting, pull requests merged in 2022-03, with the labels that each got.

#60 rename decryptBallotsEndpoint
  contracts/evoting/controller/action.go
  contracts/evoting/controller/http.go
Labels: API

#74 Node exporter
  deb-package/build-deb.sh
  deb-package/pkg/after-install.sh
  deb-package/pkg/before-remove.sh
  deb-package/pkg/etc/dedis/dvoting/network.env
  deb-package/pkg/lib/systemd/system/exporter.service
  deb-package/pkg/opt/dedis/dvoting/bin/start-exporter
  go.sum
Labels: UNICORE

#73 Frontend login button
  go.sum
  web/backend/src/Server.ts
  web/frontend/src/Routes.ts
  web/frontend/src/index.tsx
  web/frontend/src/language/en.json
  web/frontend/src/layout/App.tsx
  web/frontend/src/layout/Flash.tsx
  web/frontend/src/layout/NavBar.tsx
  web/frontend/src/mocks/handlers.ts
  web/frontend/src/pages/Home.tsx
  web/frontend/src/pages/session/HandleLogin.tsx
  web/frontend/src/pages/session/Logged.tsx
  web/frontend/src/pages/session/Login.css
  web/frontend/src/pages/session/Login.tsx
  web/frontend/src/pages/session/LoginCallback.tsx
Labels: web frontend
